# Generated by Django 4.0.5 on 2022-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='trans_id',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
