# Generated by Django 4.0.5 on 2022-07-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_desc_contact_address_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone_number',
        ),
    ]
