# Generated by Django 4.0.5 on 2022-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='payment',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
